version: 0.2

phases:
  install:
    commands:
    - add-apt-repository ppa:openjdk-r/ppa
    - apt-get update -y
    - apt-get install -y openjdk-11-jdk
    - apt-get install -y maven
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
    - echo Build started on `date`
    - mvn clean test package docker:build
    - docker images
    - docker build -t cicd:latest .
  post_build:
    commands:
    - echo Pushing the Docker image...
    - docker push cicd:latest
artifacts:
  files:
  - target/cicd-0.1.jar
  - appspec.yml
  discard-paths: yes