version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
    - echo Build started on `date`
    - mvn clean test package docker:build
  post_build:
    commands:
    - echo Pushing the Docker image...
  files:
  - target/cicd-0.1.jar
  - appspec.yml
  discard-paths: yes