version: 0.2

phases:
  install:
    commands:
    - add-apt-repository ppa:openjdk-r/ppa
    - apt-get update -y
    - apt-get install -y openjdk-11-jdk
    - apt-get install -y maven
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
    - echo Build started on `date`
    - mvn clean compile assembly:single
    - docker images
    - docker build -t cicdapp .
  post_build:
    commands:
    - echo Pushing the Docker image...
    - docker tag cicdapp:latest 195360077735.dkr.ecr.eu-west-1.amazonaws.com/cicdapp:latest
    - docker push 195360077735.dkr.ecr.eu-west-1.amazonaws.com/cicdapp:latest
artifacts:
  files:
  - target/cicd-0.1.jar
  - appspec.yml
  discard-paths: yes